2022-03-02 13:26:50,159 ERROR: Exception on /Mobplanlist [GET] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 180, in Mobplanlist
    group3 = governmentfac.query.group_by(governmentfac.govimg).all()
AttributeError: type object 'governmentfac' has no attribute 'govimg'
2022-03-02 13:29:08,321 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 13:36:51,392 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 13:43:02,089 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 13:43:08,322 ERROR: Exception on /Mobplanlist/15 [GET] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 190, in Mobplanlist
    return render_template('MobPlan.html', form=form, govlist=govlist,group2=group2, group=group)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: MobPlan.html
2022-03-02 13:43:29,235 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 14:48:50,531 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 14:51:47,578 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 15:09:19,024 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 15:09:46,408 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
