2022-04-28 18:46:56,938 ERROR: Exception on /Like [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 236, in Likee
    likeplus = likess + 1
TypeError: can only concatenate list (not "int") to list
2022-04-28 18:53:16,160 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:86]
2022-04-28 18:53:20,594 ERROR: Exception on /Like [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 236, in Likee
    likess = likess + 1
TypeError: can only concatenate list (not "int") to list
2022-04-28 18:59:41,480 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:86]
2022-04-28 18:59:51,341 ERROR: Exception on /Like [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 236, in Likee
    print(int(likess))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
2022-04-28 19:02:44,925 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:86]
2022-04-28 19:03:52,028 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:86]
2022-04-28 19:09:18,978 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:86]
